__title__ = "hier_client"
__description__ = "Python library for using Hier from the CLI."
__url__ = "https://github.com/Jessime/hier_client"
__version__ = "0.1.1"
__author__ = "Jessime Kirk"
__author_email__ = "jessime.kirk@gmail.com"
__license__ = "MIT"
